const staticQuestions = [
  // Easy Questions
  {
    question: 'What is the formula for water?',
    subject: 'Chemistry',
    topic: 'Chemical Formulas',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'Who discovered gravity?',
    subject: 'Physics',
    topic: 'Classical Mechanics',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'What is the largest mammal on Earth?',
    subject: 'Biology',
    topic: 'Zoology',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'What is the chemical symbol for oxygen?',
    subject: 'Chemistry',
    topic: 'Elements',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'Define acceleration.',
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'What is a cell membrane?',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'Name the three states of matter.',
    subject: 'Chemistry',
    topic: 'States of Matter',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'What is the unit of electrical resistance?',
    subject: 'Physics',
    topic: 'Electricity',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'What is an ecosystem?',
    subject: 'Biology',
    topic: 'Ecology',
    difficulty: 'Easy',
    marks: 5,
  },
  {
    question: 'Name the gas essential for photosynthesis.',
    subject: 'Chemistry',
    topic: 'Photosynthesis',
    difficulty: 'Easy',
    marks: 5,
  },

  // Medium Questions
  {
    question: 'Explain the process of photosynthesis.',
    subject: 'Biology',
    topic: 'Botany',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'What is the periodic table?',
    subject: 'Chemistry',
    topic: 'Chemical Elements',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'Define the concept of velocity.',
    subject: 'Physics',
    topic: 'Kinematics',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'How do enzymes function in biological systems?',
    subject: 'Biology',
    topic: 'Biochemistry',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'Explain the concept of equilibrium in chemistry.',
    subject: 'Chemistry',
    topic: 'Chemical Reactions',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'What is the Doppler effect?',
    subject: 'Physics',
    topic: 'Wave Phenomena',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'Discuss the structure of a prokaryotic cell.',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'Explain the concept of electronegativity.',
    subject: 'Chemistry',
    topic: 'Chemical Bonding',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'Define electric current.',
    subject: 'Physics',
    topic: 'Electricity',
    difficulty: 'Medium',
    marks: 10,
  },
  {
    question: 'What is the role of mitochondria in a cell?',
    subject: 'Biology',
    topic: 'Cell Biology',
    difficulty: 'Medium',
    marks: 10,
  },

  // Hard Questions
  {
    question: 'Explain the concept of quantum entanglement.',
    subject: 'Physics',
    topic: 'Quantum Mechanics',
    difficulty: 'Hard',
    marks: 20,
  },
  {
    question: 'What is the structure of DNA?',
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'Hard',
    marks: 20,
  },
  {
    question: 'Discuss the principles of organic chemistry.',
    subject: 'Chemistry',
    topic: 'Organic Chemistry',
    difficulty: 'Hard',
    marks: 20,
  },
  {
    question: 'Explain the process of protein synthesis.',
    subject: 'Biology',
    topic: 'Genetics',
    difficulty: 'Hard',
    marks: 20,
  },
  {
    question: 'Define the Heisenberg Uncertainty Principle.',
    subject: 'Physics',
    topic: 'Quantum Mechanics',
    difficulty: 'Hard',
    marks: 20,
  },
];

module.exports = staticQuestions